sonar.organization=arquisoft
sonar.host.url=https://sonarcloud.io
sonar.projectKey=Arquisoft_yovi_es1b
sonar.projectName=yovi_es1b

# Definimos el directorio base para ayudar a resolver rutas
sonar.projectBaseDir=.

# Fuentes y Tests
sonar.sources=webapp/src,users,gamey/src
sonar.tests=webapp/src/__tests__,users/__tests__,gamey/tests
sonar.test.inclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx,**/*.test.js,**/*.spec.ts,**/*.spec.tsx,**/*.spec.js
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,webapp/src/__tests__/**,users/__tests__/**,gamey/target/**,**/*.d.ts

# Cobertura
sonar.coverage.exclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx,**/*.test.js,**/*.spec.ts,**/*.spec.tsx,**/*.spec.js,**/*.d.ts,webapp/src/index.css,webapp/src/reportWebVitals.js
sonar.javascript.lcov.reportPaths=webapp/coverage/lcov.info,users/coverage/lcov.info
sonar.rust.lcov.reportPaths=gamey/lcov.info

# --- MEJORAS DE RENDIMIENTO ---
# Evitamos que el sensor de seguridad pierda tiempo con archivos gigantes o de tipos
sonar.javascript.security.maxFileSize=500
sonar.typescript.security.maxFileSize=500

# Forzamos la codificación para evitar errores de lectura en Windows/Linux
sonar.sourceEncoding=UTF-8